GET http://localhost:3000/characters/userPosts/5ed979557ae9ae3b34e74fe8

###

POST http://localhost:3000/characters/
Content-Type: application/json

{
    "name": "Moana",
    "movie": "Moana",
    "bestFriend": "Hay-Hay",
    "username": "Ellen"
}

###

PUT http://localhost:3000/characters/5edbe4cdac96b55d3cc3f1cf
Content-Type: application/json

{
    "name": "Jasmine",
    "movie": "Aladdin",
    "bestFriend": "Aladdin"
}

###

DELETE http://localhost:3000/characters/5edbe63bac96b55d3cc3f1d8

